"""fix

Revision ID: 7891bc63c14a
Revises: 96fb5ed5c3a3
Create Date: 2026-08-26 16:01:58.163698

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7891bc63c14a'
down_revision: Union[str, Sequence[str], None] = '96fb5ed5c3a3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('task', 'assignee_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('task', 'assignee_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###
